version: 2
jobs:
  build:
    docker:
    - image: docker:18.06.1-ce
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Prepare QEMU
        command: |
          docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - run:
        name: Build application Docker image
        command: |
          docker build -t "${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}" .
    - run:
        name: Push application Docker image
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            docker login -u=${DOCKER_USER} -p=${DOCKER_PASSWORD}
            docker tag "${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}" "${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}"
            docker push "${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}"
          fi